version 1.0

## XYCM germline WGS FASTQ-to-GVCF workflow
## Based on the validated SLURM test pipeline:
## FASTQ -> uBAM -> BWA-MEM2 alignment -> MergeBamAlignment
## -> MarkDuplicatesSpark -> SetNmMdAndUqTags
## -> BaseRecalibrator -> ApplyBQSR -> HaplotypeCaller GVCF
## Author: Shelley
## Date Last Modified: 2026-5-25

workflow XYCM_Germline_GVCF {
  input {
    ## Sample / read-group metadata
    String sample_name
    String sample_uid
    File fq1
    File fq2
    String read_group_id
    String library_name
    String platform_unit
    String platform_name = "DNBSEQ"
    String sequencing_center

    ## Reference bundle
    File ref_fasta
    File ref_fasta_index
    File ref_dict

    ## BWA-MEM2 index files generated by: bwa-mem2 index Homo_sapiens_assembly38.fasta
    ## These files must be localized in the same task directory as ref_fasta.
    File ref_0123
    File ref_amb
    File ref_ann
    File ref_bwt2bit64
    File ref_pac

    ## Known-sites resources for BQSR
    File dbsnp_vcf
    File dbsnp_vcf_index
    File mills_vcf
    File mills_vcf_index
    File known_indels_vcf
    File known_indels_vcf_index

    ## Executables
    String gatk_path = "gatk"
    String bwa_mem2_path = "bwa-mem2"
    String samtools_path = "samtools"

    ## Runtime parameters
    Int compression_level = 5
    Int align_threads = 16
    Int markdup_threads = 16
    Int haplotypecaller_threads = 16

    ## Conservative memory settings for production robustness.
    ## Java -Xmx is usually set to mem_gb, while runtime.memory adds headroom
    ## for native libraries, compression buffers, Spark overhead, and JVM overhead.
    Int fastq_to_sam_mem_gb = 4
    Int align_mem_gb = 14
    Int merge_mem_gb = 4
    Int markdup_mem_gb = 16
    Int fixtags_mem_gb = 16
    Int bqsr_mem_gb = 8
    Int apply_bqsr_mem_gb = 8
    Int haplotypecaller_mem_gb = 40
  }

  call FastqToSam {
    input:
      fq1 = fq1,
      fq2 = fq2,
      sample_uid = sample_uid,
      sample_name = sample_name,
      read_group_id = read_group_id,
      library_name = library_name,
      platform_unit = platform_unit,
      platform_name = platform_name,
      sequencing_center = sequencing_center,
      gatk_path = gatk_path,
      compression_level = compression_level,
      mem_gb = fastq_to_sam_mem_gb
  }

  call SamToFastqAndBwaMem2 {
    input:
      input_bam = FastqToSam.output_bam,
      sample_uid = sample_uid,
      ref_fasta = ref_fasta,
      ref_fasta_index = ref_fasta_index,
      ref_dict = ref_dict,
      ref_0123 = ref_0123,
      ref_amb = ref_amb,
      ref_ann = ref_ann,
      ref_bwt2bit64 = ref_bwt2bit64,
      ref_pac = ref_pac,
      gatk_path = gatk_path,
      bwa_mem2_path = bwa_mem2_path,
      samtools_path = samtools_path,
      compression_level = compression_level,
      threads = align_threads,
      mem_gb = align_mem_gb
  }

  call MergeBamAlignment {
    input:
      unmapped_bam = FastqToSam.output_bam,
      aligned_bam = SamToFastqAndBwaMem2.output_bam,
      sample_uid = sample_uid,
      ref_fasta = ref_fasta,
      ref_fasta_index = ref_fasta_index,
      ref_dict = ref_dict,
      bwa_commandline = SamToFastqAndBwaMem2.bwa_commandline,
      bwa_version = SamToFastqAndBwaMem2.bwa_version,
      gatk_path = gatk_path,
      samtools_path = samtools_path,
      compression_level = compression_level,
      mem_gb = merge_mem_gb
  }

  call MarkDuplicatesSpark {
    input:
      input_bam = MergeBamAlignment.output_bam,
      sample_uid = sample_uid,
      gatk_path = gatk_path,
      samtools_path = samtools_path,
      threads = markdup_threads,
      mem_gb = markdup_mem_gb
  }

  call SetNmMdAndUqTags {
    input:
      input_bam = MarkDuplicatesSpark.output_bam,
      input_bam_index = MarkDuplicatesSpark.output_bam_index,
      sample_uid = sample_uid,
      ref_fasta = ref_fasta,
      ref_fasta_index = ref_fasta_index,
      ref_dict = ref_dict,
      gatk_path = gatk_path,
      samtools_path = samtools_path,
      compression_level = compression_level,
      mem_gb = fixtags_mem_gb
  }

  call BaseRecalibrator {
    input:
      input_bam = SetNmMdAndUqTags.output_bam,
      input_bam_index = SetNmMdAndUqTags.output_bam_index,
      sample_uid = sample_uid,
      ref_fasta = ref_fasta,
      ref_fasta_index = ref_fasta_index,
      ref_dict = ref_dict,
      dbsnp_vcf = dbsnp_vcf,
      dbsnp_vcf_index = dbsnp_vcf_index,
      mills_vcf = mills_vcf,
      mills_vcf_index = mills_vcf_index,
      known_indels_vcf = known_indels_vcf,
      known_indels_vcf_index = known_indels_vcf_index,
      gatk_path = gatk_path,
      mem_gb = bqsr_mem_gb
  }

  call ApplyBQSR {
    input:
      input_bam = SetNmMdAndUqTags.output_bam,
      input_bam_index = SetNmMdAndUqTags.output_bam_index,
      recal_report = BaseRecalibrator.recal_report,
      sample_uid = sample_uid,
      ref_fasta = ref_fasta,
      ref_fasta_index = ref_fasta_index,
      ref_dict = ref_dict,
      gatk_path = gatk_path,
      samtools_path = samtools_path,
      mem_gb = apply_bqsr_mem_gb
  }

  call HaplotypeCallerGVCF {
    input:
      input_bam = ApplyBQSR.output_bam,
      input_bam_index = ApplyBQSR.output_bam_index,
      sample_uid = sample_uid,
      ref_fasta = ref_fasta,
      ref_fasta_index = ref_fasta_index,
      ref_dict = ref_dict,
      gatk_path = gatk_path,
      threads = haplotypecaller_threads,
      mem_gb = haplotypecaller_mem_gb
  }

  output {
    File gvcf = HaplotypeCallerGVCF.output_gvcf
    File gvcf_index = HaplotypeCallerGVCF.output_gvcf_index

    File duplicate_metrics = MarkDuplicatesSpark.metrics_file
    File recal_report = BaseRecalibrator.recal_report

    File fastq_to_sam_log = FastqToSam.gatk_log
    File align_log = SamToFastqAndBwaMem2.pipeline_log
    File bwa_stderr_log = SamToFastqAndBwaMem2.bwa_stderr_log
    File merge_log = MergeBamAlignment.gatk_log
    File markdup_log = MarkDuplicatesSpark.gatk_log
    File fixtags_log = SetNmMdAndUqTags.gatk_log
    File bqsr_log = BaseRecalibrator.gatk_log
    File apply_bqsr_log = ApplyBQSR.gatk_log
    File haplotypecaller_log = HaplotypeCallerGVCF.gatk_log

    File fastq_to_sam_time = FastqToSam.time_log
    File align_time = SamToFastqAndBwaMem2.time_log
    File merge_time = MergeBamAlignment.time_log
    File markdup_time = MarkDuplicatesSpark.time_log
    File fixtags_time = SetNmMdAndUqTags.time_log
    File bqsr_time = BaseRecalibrator.time_log
    File apply_bqsr_time = ApplyBQSR.time_log
    File haplotypecaller_time = HaplotypeCallerGVCF.time_log
  }
}

task FastqToSam {
  input {
    File fq1
    File fq2
    String sample_uid
    String sample_name
    String read_group_id
    String library_name
    String platform_unit
    String platform_name
    String sequencing_center
    String gatk_path
    Int compression_level
    Int mem_gb
  }

  command <<<
    set -euo pipefail
    mkdir -p tmp

    echo "Using GATK:"
    which ~{gatk_path} || true
    ~{gatk_path} --version

    test -s ~{fq1}
    test -s ~{fq2}

    /usr/bin/time -v -o ~{sample_uid}.FastqToSam.time.log \
    ~{gatk_path} --java-options "-Dsamjdk.compression_level=~{compression_level} -Xms~{mem_gb}G -Xmx~{mem_gb}G -Djava.io.tmpdir=tmp" \
      FastqToSam \
      FASTQ=~{fq1} \
      FASTQ2=~{fq2} \
      OUTPUT=~{sample_uid}.unmapped.bam \
      READ_GROUP_NAME="~{read_group_id}" \
      SAMPLE_NAME="~{sample_name}" \
      LIBRARY_NAME="~{library_name}" \
      PLATFORM_UNIT="~{platform_unit}" \
      PLATFORM="~{platform_name}" \
      SEQUENCING_CENTER="~{sequencing_center}" \
      CREATE_MD5_FILE=true \
      TMP_DIR=tmp \
      > ~{sample_uid}.FastqToSam.log 2>&1

    test -s ~{sample_uid}.unmapped.bam
  >>>

  runtime {
    cpu: 2
    memory: "~{mem_gb + 2} GB"
  }

  output {
    File output_bam = "~{sample_uid}.unmapped.bam"
    File output_md5 = "~{sample_uid}.unmapped.bam.md5"
    File gatk_log = "~{sample_uid}.FastqToSam.log"
    File time_log = "~{sample_uid}.FastqToSam.time.log"
  }
}

task SamToFastqAndBwaMem2 {
  input {
    File input_bam
    String sample_uid
    File ref_fasta
    File ref_fasta_index
    File ref_dict
    File ref_0123
    File ref_amb
    File ref_ann
    File ref_bwt2bit64
    File ref_pac
    String gatk_path
    String bwa_mem2_path
    String samtools_path
    Int compression_level
    Int threads
    Int mem_gb
  }

  String bwa_cmd = "bwa-mem2 mem -K 100000000 -p -v 3 -t " + threads + " -Y " + basename(ref_fasta)

  command <<<
    set -euo pipefail
    mkdir -p tmp

    echo "Using GATK:"
    ~{gatk_path} --version
    echo "Using BWA-MEM2:"
    ~{bwa_mem2_path} version || true
    echo "Using samtools:"
    ~{samtools_path} --version | head -n 1

    test -s ~{input_bam}
    test -s ~{ref_fasta}
    test -s ~{ref_fasta_index}
    test -s ~{ref_dict}
    test -s ~{ref_0123}
    test -s ~{ref_amb}
    test -s ~{ref_ann}
    test -s ~{ref_bwt2bit64}
    test -s ~{ref_pac}

    # Keep BWA-MEM2 version for MergeBamAlignment PG record.
    ~{bwa_mem2_path} version 2>&1 | head -n 1 > ~{sample_uid}.bwa-mem2.version.txt || true

    /usr/bin/time -v -o ~{sample_uid}.SamToFastqAndBwaMem2.time.log \
    bash -c '
      set -o pipefail
      ~{gatk_path} --java-options "-Dsamjdk.compression_level=~{compression_level} -Xms4G -Xmx~{mem_gb}G -Djava.io.tmpdir=tmp" \
        SamToFastq \
        INPUT=~{input_bam} \
        FASTQ=/dev/stdout \
        INTERLEAVE=true \
        NON_PF=true \
      | \
      ~{bwa_mem2_path} mem \
        -K 100000000 \
        -p \
        -v 3 \
        -t ~{threads} \
        -Y \
        ~{ref_fasta} \
        /dev/stdin \
        2> ~{sample_uid}.bwa-mem2.stderr.log \
      | \
      ~{samtools_path} view -1 -o ~{sample_uid}.unmerged.bam -
    ' > ~{sample_uid}.SamToFastqAndBwaMem2.pipeline.log 2>&1

    ~{samtools_path} quickcheck ~{sample_uid}.unmerged.bam
    test -s ~{sample_uid}.unmerged.bam
  >>>

  runtime {
    cpu: threads
    memory: "~{mem_gb + 4} GB"
  }

  output {
    File output_bam = "~{sample_uid}.unmerged.bam"
    File bwa_stderr_log = "~{sample_uid}.bwa-mem2.stderr.log"
    File pipeline_log = "~{sample_uid}.SamToFastqAndBwaMem2.pipeline.log"
    File time_log = "~{sample_uid}.SamToFastqAndBwaMem2.time.log"
    File bwa_version_file = "~{sample_uid}.bwa-mem2.version.txt"
    String bwa_version = read_string("~{sample_uid}.bwa-mem2.version.txt")
    String bwa_commandline = "~{bwa_cmd}"
  }
}

task MergeBamAlignment {
  input {
    File unmapped_bam
    File aligned_bam
    String sample_uid
    File ref_fasta
    File ref_fasta_index
    File ref_dict
    String bwa_commandline
    String bwa_version
    String gatk_path
    String samtools_path
    Int compression_level
    Int mem_gb
  }

  command <<<
    set -euo pipefail
    mkdir -p tmp

    /usr/bin/time -v -o ~{sample_uid}.MergeBamAlignment.time.log \
    ~{gatk_path} --java-options "-Dsamjdk.compression_level=~{compression_level} -Xms~{mem_gb}G -Xmx~{mem_gb}G -Djava.io.tmpdir=tmp" \
      MergeBamAlignment \
      --VALIDATION_STRINGENCY SILENT \
      --EXPECTED_ORIENTATIONS FR \
      --ATTRIBUTES_TO_RETAIN X0 \
      --ALIGNED_BAM ~{aligned_bam} \
      --UNMAPPED_BAM ~{unmapped_bam} \
      --OUTPUT ~{sample_uid}.aligned.unsorted.bam \
      --REFERENCE_SEQUENCE ~{ref_fasta} \
      --PAIRED_RUN true \
      --SORT_ORDER "unsorted" \
      --IS_BISULFITE_SEQUENCE false \
      --ALIGNED_READS_ONLY false \
      --CLIP_ADAPTERS false \
      --MAX_RECORDS_IN_RAM 2000000 \
      --ADD_MATE_CIGAR true \
      --MAX_INSERTIONS_OR_DELETIONS -1 \
      --PRIMARY_ALIGNMENT_STRATEGY MostDistant \
      --PROGRAM_RECORD_ID "bwamem" \
      --PROGRAM_GROUP_VERSION "~{bwa_version}" \
      --PROGRAM_GROUP_COMMAND_LINE "~{bwa_commandline}" \
      --PROGRAM_GROUP_NAME "bwamem" \
      --UNMAPPED_READ_STRATEGY COPY_TO_TAG \
      --ALIGNER_PROPER_PAIR_FLAGS true \
      --UNMAP_CONTAMINANT_READS true \
      > ~{sample_uid}.MergeBamAlignment.log 2>&1

    ~{samtools_path} quickcheck ~{sample_uid}.aligned.unsorted.bam
    test -s ~{sample_uid}.aligned.unsorted.bam
  >>>

  runtime {
    cpu: 4
    memory: "~{mem_gb + 4} GB"
  }

  output {
    File output_bam = "~{sample_uid}.aligned.unsorted.bam"
    File gatk_log = "~{sample_uid}.MergeBamAlignment.log"
    File time_log = "~{sample_uid}.MergeBamAlignment.time.log"
  }
}

task MarkDuplicatesSpark {
  input {
    File input_bam
    String sample_uid
    String gatk_path
    String samtools_path
    Int threads
    Int mem_gb
  }

  command <<<
    set -euo pipefail
    mkdir -p tmp

    /usr/bin/time -v -o ~{sample_uid}.MarkDuplicatesSpark.time.log \
    ~{gatk_path} --java-options "-Xms8G -Xmx~{mem_gb}G -Djava.io.tmpdir=tmp" \
      MarkDuplicatesSpark \
      -I ~{input_bam} \
      -O ~{sample_uid}.aligned.duplicates_marked.sorted.bam \
      -M ~{sample_uid}.duplicate_metrics.txt \
      --spark-master local[~{threads}] \
      --conf "spark.local.dir=tmp" \
      --conf "spark.executor.cores=~{threads}" \
      --create-output-bam-index true \
      > ~{sample_uid}.MarkDuplicatesSpark.log 2>&1

    ~{samtools_path} quickcheck ~{sample_uid}.aligned.duplicates_marked.sorted.bam
    test -s ~{sample_uid}.aligned.duplicates_marked.sorted.bam

    # Normalize possible GATK index naming differences to a stable downstream filename.
    if [[ -s ~{sample_uid}.aligned.duplicates_marked.sorted.bam.bai ]]; then
      true
    elif [[ -s ~{sample_uid}.aligned.duplicates_marked.sorted.bai ]]; then
      ln -sf ~{sample_uid}.aligned.duplicates_marked.sorted.bai ~{sample_uid}.aligned.duplicates_marked.sorted.bam.bai
    else
      echo "ERROR: missing MarkDuplicatesSpark BAM index" >&2
      exit 1
    fi

    test -s ~{sample_uid}.duplicate_metrics.txt
  >>>

  runtime {
    cpu: threads
    memory: "~{mem_gb + 8} GB"
  }

  output {
    File output_bam = "~{sample_uid}.aligned.duplicates_marked.sorted.bam"
    File output_bam_index = "~{sample_uid}.aligned.duplicates_marked.sorted.bam.bai"
    File metrics_file = "~{sample_uid}.duplicate_metrics.txt"
    File gatk_log = "~{sample_uid}.MarkDuplicatesSpark.log"
    File time_log = "~{sample_uid}.MarkDuplicatesSpark.time.log"
  }
}

task SetNmMdAndUqTags {
  input {
    File input_bam
    File input_bam_index
    String sample_uid
    File ref_fasta
    File ref_fasta_index
    File ref_dict
    String gatk_path
    String samtools_path
    Int compression_level
    Int mem_gb
  }

  command <<<
    set -euo pipefail
    mkdir -p tmp

    /usr/bin/time -v -o ~{sample_uid}.SetNmMdAndUqTags.time.log \
    ~{gatk_path} --java-options "-Dsamjdk.compression_level=~{compression_level} -Xms4G -Xmx~{mem_gb}G -Djava.io.tmpdir=tmp" \
      SetNmMdAndUqTags \
      --INPUT ~{input_bam} \
      --OUTPUT ~{sample_uid}.aligned.duplicates_marked.sorted.fixed.bam \
      --CREATE_INDEX true \
      --CREATE_MD5_FILE true \
      --REFERENCE_SEQUENCE ~{ref_fasta} \
      > ~{sample_uid}.SetNmMdAndUqTags.log 2>&1

    ~{samtools_path} quickcheck ~{sample_uid}.aligned.duplicates_marked.sorted.fixed.bam
    test -s ~{sample_uid}.aligned.duplicates_marked.sorted.fixed.bam
    test -s ~{sample_uid}.aligned.duplicates_marked.sorted.fixed.bai
  >>>

  runtime {
    cpu: 4
    memory: "~{mem_gb + 4} GB"
  }

  output {
    File output_bam = "~{sample_uid}.aligned.duplicates_marked.sorted.fixed.bam"
    File output_bam_index = "~{sample_uid}.aligned.duplicates_marked.sorted.fixed.bai"
    File output_md5 = "~{sample_uid}.aligned.duplicates_marked.sorted.fixed.bam.md5"
    File gatk_log = "~{sample_uid}.SetNmMdAndUqTags.log"
    File time_log = "~{sample_uid}.SetNmMdAndUqTags.time.log"
  }
}

task BaseRecalibrator {
  input {
    File input_bam
    File input_bam_index
    String sample_uid
    File ref_fasta
    File ref_fasta_index
    File ref_dict
    File dbsnp_vcf
    File dbsnp_vcf_index
    File mills_vcf
    File mills_vcf_index
    File known_indels_vcf
    File known_indels_vcf_index
    String gatk_path
    Int mem_gb
  }

  command <<<
    set -euo pipefail
    mkdir -p tmp

    /usr/bin/time -v -o ~{sample_uid}.BaseRecalibrator.time.log \
    ~{gatk_path} --java-options "-Xms4G -Xmx~{mem_gb}G -Djava.io.tmpdir=tmp" \
      BaseRecalibrator \
      -R ~{ref_fasta} \
      -I ~{input_bam} \
      -O ~{sample_uid}.recal_data.csv \
      --known-sites ~{dbsnp_vcf} \
      --known-sites ~{mills_vcf} \
      --known-sites ~{known_indels_vcf} \
      > ~{sample_uid}.BaseRecalibrator.log 2>&1

    test -s ~{sample_uid}.recal_data.csv
  >>>

  runtime {
    cpu: 4
    memory: "~{mem_gb + 4} GB"
  }

  output {
    File recal_report = "~{sample_uid}.recal_data.csv"
    File gatk_log = "~{sample_uid}.BaseRecalibrator.log"
    File time_log = "~{sample_uid}.BaseRecalibrator.time.log"
  }
}

task ApplyBQSR {
  input {
    File input_bam
    File input_bam_index
    File recal_report
    String sample_uid
    File ref_fasta
    File ref_fasta_index
    File ref_dict
    String gatk_path
    String samtools_path
    Int mem_gb
  }

  command <<<
    set -euo pipefail
    mkdir -p tmp

    /usr/bin/time -v -o ~{sample_uid}.ApplyBQSR.time.log \
    ~{gatk_path} --java-options "-Xms4G -Xmx~{mem_gb}G -Djava.io.tmpdir=tmp" \
      ApplyBQSR \
      -R ~{ref_fasta} \
      -I ~{input_bam} \
      -O ~{sample_uid}.aligned.duplicates_marked.recalibrated.bam \
      -bqsr ~{recal_report} \
      --add-output-sam-program-record \
      --create-output-bam-md5 \
      > ~{sample_uid}.ApplyBQSR.log 2>&1

    ~{samtools_path} quickcheck ~{sample_uid}.aligned.duplicates_marked.recalibrated.bam
    test -s ~{sample_uid}.aligned.duplicates_marked.recalibrated.bam
    test -s ~{sample_uid}.aligned.duplicates_marked.recalibrated.bai
  >>>

  runtime {
    cpu: 4
    memory: "~{mem_gb + 4} GB"
  }

  output {
    File output_bam = "~{sample_uid}.aligned.duplicates_marked.recalibrated.bam"
    File output_bam_index = "~{sample_uid}.aligned.duplicates_marked.recalibrated.bai"
    File output_md5 = "~{sample_uid}.aligned.duplicates_marked.recalibrated.bam.md5"
    File gatk_log = "~{sample_uid}.ApplyBQSR.log"
    File time_log = "~{sample_uid}.ApplyBQSR.time.log"
  }
}

task HaplotypeCallerGVCF {
  input {
    File input_bam
    File input_bam_index
    String sample_uid
    File ref_fasta
    File ref_fasta_index
    File ref_dict
    String gatk_path
    Int threads
    Int mem_gb
  }

  command <<<
    set -euo pipefail
    mkdir -p tmp

    /usr/bin/time -v -o ~{sample_uid}.HaplotypeCaller.time.log \
    ~{gatk_path} --java-options "-Xms~{mem_gb}G -Xmx~{mem_gb}G -XX:ParallelGCThreads=2 -Djava.io.tmpdir=tmp" \
      HaplotypeCaller \
      -R ~{ref_fasta} \
      -I ~{input_bam} \
      -O ~{sample_uid}.g.vcf.gz \
      -ERC GVCF \
      --native-pair-hmm-threads ~{threads} \
      > ~{sample_uid}.HaplotypeCaller.log 2>&1

    test -s ~{sample_uid}.g.vcf.gz
    test -s ~{sample_uid}.g.vcf.gz.tbi
  >>>

  runtime {
    cpu: threads
    memory: "~{mem_gb + 8} GB"
  }

  output {
    File output_gvcf = "~{sample_uid}.g.vcf.gz"
    File output_gvcf_index = "~{sample_uid}.g.vcf.gz.tbi"
    File gatk_log = "~{sample_uid}.HaplotypeCaller.log"
    File time_log = "~{sample_uid}.HaplotypeCaller.time.log"
  }
}
