#!/usr/bin/env bash
#SBATCH --job-name=XYCM_GenotypeGVCFs
#SBATCH --partition=cpuQ
#SBATCH --qos=cpuq
#SBATCH --account=pi_dengguangtong
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=20G
#SBATCH --array=1-25
#SBATCH --output=/public/home/hpc8301200407/XYCM_WGS/Variant_Calling/WDL/Joint_Genotyping/GenotypeGVCFs/logs/GenotypeGVCFs.%A_%a.out
#SBATCH --error=/public/home/hpc8301200407/XYCM_WGS/Variant_Calling/WDL/Joint_Genotyping/GenotypeGVCFs/logs/GenotypeGVCFs.%A_%a.err


set -euo pipefail


# ==============================================================================
# XYCM WGS Joint Genotyping Pipeline
# Step 4. GenotypeGVCFs
#
# Purpose:
#   Perform joint genotyping from chromosome-specific GenomicsDB workspaces.
#
# Input:
#   GenomicsDB workspace generated by Step 3.
#
# Output:
#   chromosome-specific cohort VCF:
#
#   XYCM.chrN.raw.vcf.gz
#
# Chromosomes:
#   chr1-chr22, chrX, chrY, chrM
#
# Cohort:
#   449 technical samples, including five intended technical replicate pairs.
# ==============================================================================


# ------------------------------------------------------------------------------
# 0. Configuration
# ------------------------------------------------------------------------------

JOINT_DIR="/public/home/hpc8301200407/XYCM_WGS/Variant_Calling/WDL/Joint_Genotyping"

WORK_DIR="${JOINT_DIR}/GenotypeGVCFs"

GENOMICSDB_DIR="${JOINT_DIR}/GenomicsDBImport/genomicsdb"

REF_DIR="/public/home/hpc8301200407/XYCM_WGS/Variant_Calling/Resource.bundle/GATK.hg38"

REF="${REF_DIR}/Homo_sapiens_assembly38.fasta"
REF_FAI="${REF}.fai"
REF_DICT="${REF_DIR}/Homo_sapiens_assembly38.dict"


OUT_DIR="${WORK_DIR}/raw_vcf"
TMP_ROOT="${WORK_DIR}/tmp"
STATUS_DIR="${WORK_DIR}/status"


# ------------------------------------------------------------------------------
# 1. Environment
# ------------------------------------------------------------------------------

source "${HOME}/miniconda3/etc/profile.d/conda.sh"
conda activate gatk_germline


command -v gatk >/dev/null 2>&1 || {
    echo "ERROR: gatk is unavailable." >&2
    exit 1
}


mkdir -p \
    "${OUT_DIR}" \
    "${TMP_ROOT}" \
    "${STATUS_DIR}"



# ------------------------------------------------------------------------------
# 2. Chromosome assignment
# ------------------------------------------------------------------------------

CHROMS=(
    chr1
    chr2
    chr3
    chr4
    chr5
    chr6
    chr7
    chr8
    chr9
    chr10
    chr11
    chr12
    chr13
    chr14
    chr15
    chr16
    chr17
    chr18
    chr19
    chr20
    chr21
    chr22
    chrX
    chrY
    chrM
)


if [[ "${SLURM_ARRAY_TASK_ID}" -lt 1 || \
      "${SLURM_ARRAY_TASK_ID}" -gt "${#CHROMS[@]}" ]]; then

    echo "ERROR: invalid array task ID" >&2
    exit 1
fi


IDX=$((SLURM_ARRAY_TASK_ID - 1))

CHR="${CHROMS[$IDX]}"


DB="${GENOMICSDB_DIR}/${CHR}"

TMP="${TMP_ROOT}/${CHR}"

OUT_VCF="${OUT_DIR}/XYCM.${CHR}.raw.vcf.gz"

SUCCESS_FILE="${STATUS_DIR}/${CHR}.success"



# ------------------------------------------------------------------------------
# 3. Reference sanity checks
# ------------------------------------------------------------------------------

if [[ ! -s "${REF}" ]]; then
    echo "ERROR: missing reference fasta:"
    echo "${REF}"
    exit 1
fi


if [[ ! -s "${REF_FAI}" ]]; then
    echo "ERROR: missing fasta index:"
    echo "${REF_FAI}"
    exit 1
fi


if [[ ! -s "${REF_DICT}" ]]; then
    echo "ERROR: missing sequence dictionary:"
    echo "${REF_DICT}"
    exit 1
fi



# ------------------------------------------------------------------------------
# 4. GenomicsDB workspace sanity checks
# ------------------------------------------------------------------------------

if [[ ! -d "${DB}" ]]; then

    echo "ERROR: GenomicsDB workspace missing:"
    echo "${DB}"

    exit 1
fi


if [[ ! -s "${DB}/callset.json" ]]; then

    echo "ERROR: missing callset.json:"
    echo "${DB}/callset.json"

    exit 1
fi


if [[ ! -s "${DB}/vidmap.json" ]]; then

    echo "ERROR: missing vidmap.json:"
    echo "${DB}/vidmap.json"

    exit 1
fi



# ------------------------------------------------------------------------------
# 5. Prevent accidental overwrite
# ------------------------------------------------------------------------------

if [[ -e "${OUT_VCF}" ]]; then

    echo "ERROR: output already exists:"
    echo "${OUT_VCF}"

    exit 1
fi


rm -rf "${TMP}"

mkdir -p "${TMP}"

rm -f "${SUCCESS_FILE}"



# ------------------------------------------------------------------------------
# 6. Job information
# ------------------------------------------------------------------------------

echo "=============================================================================="
echo "XYCM WGS - GenotypeGVCFs"
echo "=============================================================================="
echo "Start time          : $(date --iso-8601=seconds)"
echo "Hostname            : $(hostname)"
echo "SLURM job ID        : ${SLURM_JOB_ID}"
echo "Array task          : ${SLURM_ARRAY_TASK_ID}"
echo "Chromosome          : ${CHR}"
echo "GenomicsDB          : ${DB}"
echo "Output              : ${OUT_VCF}"
echo "Reference           : ${REF}"
echo "CPUs                : ${SLURM_CPUS_PER_TASK}"
echo "Memory              : ${SLURM_MEM_PER_NODE:-NA}"
echo "=============================================================================="

echo

gatk --version



# ------------------------------------------------------------------------------
# 7. GenotypeGVCFs
#
# -V gendb://
#   Reads the chromosome-specific GenomicsDB workspace.
#
# -L
#   Restricts genotyping to this chromosome.
#
# Output:
#   compressed VCF.gz
# ------------------------------------------------------------------------------

gatk \
    --java-options "-Xms4G -Xmx16G -XX:ParallelGCThreads=4 -Djava.io.tmpdir=${TMP}" \
    GenotypeGVCFs \
    -R "${REF}" \
    -V "gendb://${DB}" \
    -L "${CHR}" \
    -O "${OUT_VCF}"



# ------------------------------------------------------------------------------
# 8. Validate output
# ------------------------------------------------------------------------------

if [[ ! -s "${OUT_VCF}" ]]; then

    echo "ERROR: output VCF missing or empty:"
    echo "${OUT_VCF}"

    exit 1
fi


if [[ ! -s "${OUT_VCF}.tbi" ]]; then

    echo "ERROR: VCF index missing:"
    echo "${OUT_VCF}.tbi"

    exit 1
fi



# ------------------------------------------------------------------------------
# 9. Success marker
# ------------------------------------------------------------------------------

{
    echo "chromosome=${CHR}"
    echo "output=${OUT_VCF}"
    echo "workspace=${DB}"
    echo "reference=${REF}"
    echo "slurm_job_id=${SLURM_JOB_ID}"
    echo "slurm_array_task_id=${SLURM_ARRAY_TASK_ID}"
    echo "completed=$(date --iso-8601=seconds)"

} > "${SUCCESS_FILE}"



# ------------------------------------------------------------------------------
# 10. Cleanup
# ------------------------------------------------------------------------------

rm -rf "${TMP}"



# ------------------------------------------------------------------------------
# 11. Final report
# ------------------------------------------------------------------------------

echo
echo "=============================================================================="
echo "SUCCESS: GenotypeGVCFs completed"
echo "=============================================================================="
echo "Chromosome : ${CHR}"
echo "Output     : ${OUT_VCF}"
echo "Status     : ${SUCCESS_FILE}"
echo "End time   : $(date --iso-8601=seconds)"
echo "=============================================================================="